import { BadRequestException, Injectable, PipeTransform } from '@nestjs/common';

/**
 * Validates that a route parameter is a valid CUID.
 *
 * CUIDs generated by Prisma's `@default(cuid())` are 25-character strings
 * consisting of lowercase letters and digits, always starting with 'c'.
 *
 * This pipe rejects obviously invalid IDs early, preventing unnecessary
 * database queries with malformed identifiers.
 */
@Injectable()
export class ParseCuidPipe implements PipeTransform<string, string> {
  // CUID v1: starts with 'c', 25 chars, lowercase alphanumeric
  private static readonly CUID_REGEX = /^c[a-z0-9]{24}$/;

  transform(value: string): string {
    if (!value || !ParseCuidPipe.CUID_REGEX.test(value)) {
      throw new BadRequestException('Invalid ID format');
    }
    return value;
  }
}
