#!/usr/bin/env bash
# =============================================================================
# Interactive Environment Setup
# Generates deploy/.env.prod with your settings
#
# Usage: bash deploy/setup-env.sh
# =============================================================================

set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.prod"

echo -e "${CYAN}━━━ Homework AI Environment Setup ━━━${NC}"
echo ""

if [[ -f "$ENV_FILE" ]]; then
  echo -e "${YELLOW}$ENV_FILE already exists.${NC}"
  read -p "Overwrite? (y/N): " overwrite
  [[ "$overwrite" != "y" && "$overwrite" != "Y" ]] && { echo "Aborted."; exit 0; }
fi

# Helper functions
rand_pass() { openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"; }

prompt() {
  local var_name="$1"
  local description="$2"
  local default_val="${3:-}"
  local is_secret="${4:-false}"

  if [[ "$is_secret" == "true" ]]; then
    if [[ -n "$default_val" ]]; then
      read -sp "$description [$default_val]: " value
      echo ""
    else
      read -sp "$description: " value
      echo ""
    fi
  else
    read -p "$description [$default_val]: " value
  fi

  value="${value:-$default_val}"
  eval "$var_name='$value'"
}

# --- Collect settings ---
echo -e "${GREEN}Database Settings${NC}"
prompt DB_NAME     "Database name"          "homework_ai"
prompt DB_USER     "Database user"          "homework_ai"
prompt DB_PASS     "Database password"      "$(rand_pass 24)" true
prompt DB_ROOT_PASS "MySQL root password"   "$(rand_pass 24)" true

echo ""
echo -e "${GREEN}Security${NC}"
prompt JWT_SECRET  "JWT secret (min 32 chars)" "$(rand_pass 48)" true

echo ""
echo -e "${GREEN}Web Settings${NC}"
prompt WEB_PORT    "Web port"               "80"
prompt DOMAIN      "Domain name"            "localhost"

CORS_VAL="http://$DOMAIN"
[[ "$WEB_PORT" != "80" ]] && CORS_VAL="http://$DOMAIN:$WEB_PORT"
prompt CORS_ORIGIN "CORS origin"            "$CORS_VAL"

echo ""
echo -e "${GREEN}MinIO (Object Storage)${NC}"
prompt MINIO_USER  "MinIO user"             "minioadmin"
prompt MINIO_PASS  "MinIO password"         "$(rand_pass 24)" true
prompt MINIO_BUCKET "MinIO bucket"          "submissions"

echo ""
echo -e "${GREEN}AI Services (can configure later in admin panel)${NC}"
prompt OCR_KEY     "Baidu OCR API Key"      ""
prompt OCR_SECRET  "Baidu OCR Secret Key"   ""
prompt LLM_KEY     "LLM API Key"            ""
prompt LLM_URL     "LLM Base URL"           ""
prompt LLM_MODEL   "LLM Model"             ""

echo ""
echo -e "${GREEN}Email (optional)${NC}"
prompt SMTP_HOST   "SMTP Host"              ""
prompt SMTP_PORT   "SMTP Port"              "587"
prompt SMTP_USER   "SMTP User"              ""
prompt SMTP_PASS_VAL "SMTP Password"        "" true
prompt SMTP_FROM   "SMTP From Address"      "noreply@$DOMAIN"

echo ""
echo -e "${GREEN}Scaling${NC}"
prompt API_REPLICAS    "API replicas"        "1"
prompt WORKER_REPLICAS "Worker replicas"     "1"
prompt WORKER_CONCURRENCY "Worker concurrency" "5"

# --- Write file ---
cat > "$ENV_FILE" << EOF
# Generated by setup-env.sh on $(date -Iseconds)

DB_PASS=$DB_PASS
DB_ROOT_PASSWORD=$DB_ROOT_PASS
DB_NAME=$DB_NAME
DB_USER=$DB_USER

JWT_SECRET=$JWT_SECRET

WEB_PORT=$WEB_PORT
CORS_ORIGIN=$CORS_ORIGIN

MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PASS
MINIO_BUCKET=$MINIO_BUCKET

BAIDU_OCR_API_KEY=$OCR_KEY
BAIDU_OCR_SECRET_KEY=$OCR_SECRET
LLM_API_KEY=$LLM_KEY
LLM_BASE_URL=$LLM_URL
LLM_MODEL=$LLM_MODEL

SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS_VAL
SMTP_FROM=$SMTP_FROM

API_REPLICAS=$API_REPLICAS
WORKER_REPLICAS=$WORKER_REPLICAS
WORKER_CONCURRENCY=$WORKER_CONCURRENCY
EOF

chmod 600 "$ENV_FILE"

echo ""
echo -e "${GREEN}━━━ Environment file created: $ENV_FILE ━━━${NC}"
echo -e "Next: ${CYAN}bash deploy/quick-deploy.sh${NC}"
